### ISSUE TITLE
Support for video

### ISSUE THREAD

**Issue by e-roy** [googleapis/nodejs-vertexai#104]
Will there be support to use video data like the `@google-cloud/vertexai` library?

**Comment by sararob** [comment]
This is the GitHub repo for the `@google-cloud/vertexai` npm package. Video data is supported, here's an example (also in the readme):

```
async function multiPartContentVideo() {
    const filePart = {file_data: {file_uri: 'gs://cloud-samples-data/video/animals.mp4', mime_type: 'video/mp4'}};
    const textPart = {text: 'What is in the video?'};
    const request = {
        contents: [{role: 'user', parts: [textPart, filePart]}],
      };
    const streamingResp = await generativeVisionModel.generateContentStream(request);
    for await (const item of streamingResp.stream) {
      console.log('stream chunk: ', JSON.stringify(item));
    }
    const aggregatedResponse = await streamingResp.response;
    console.log(aggregatedResponse.candidates[0].content);
}

multiPartContentVideo();
```

**Comment by e-roy** [comment]
My apologies!  I had too many tabs open and meant to open this issue in the `@google/generative-ai` package.

The `@google-cloud/vertexai` does support video and does it well!  Using the `@google-cloud/generative-ai` is easier using for building and deploying with something like Next.js.  An API key is easier to handle and hide than using `service-account.json`

Sorry again and thank you!

**Comment by sararob** [comment]
No worries, thank you for the feedback re: Next.js!
