### ISSUE TITLE
How can i install v0.2.0 with npm

### ISSUE THREAD

**Issue by keepsaunter** [googleapis/nodejs-vertexai#127]
I canot get the 0.2 version of this package with npm:
![image](https://github.com/googleapis/nodejs-vertexai/assets/29244475/1fcfae1f-3fd2-403b-9e0d-479a5677b21b)

So i canot install v0.2.0 with npm?

**Comment by boarush** [comment]
Try installing the latest version using `npm install @google-cloud/vertexai@latest`.

**Comment by yyyu-google** [comment]
Hi @keepsaunter 
As per timestamp of this comment, I have just checked on this command
`npm view @google-cloud/vertexai versions`
It shows the versions as 
`[ '0.1.0', '0.1.1', '0.1.2', '0.1.3', '0.2.0', '0.2.1' ]` 

If you prefer to specify a version , you should be able to install any of the versions listed above.
If you just want to have the latest installed, what @boarush suggested should work. 

Hope this helps
