### ISSUE TITLE
Using the text-bison model returns a BadRequest response

### ISSUE THREAD

**Issue by aaronzhongg** [googleapis/nodejs-vertexai#135]
text-bison model returns a 400 BadRequest response

#### Environment details

  - Programming language: Node.js
  - OS: MacOS
  - Language runtime version: v20.11.0
  - Package version: 0.2.1

#### Steps to reproduce

The example provided in the [nodejs-docs-sample repo](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/generative-ai/snippets/nonStreamingContent.js) works with the `gemini-pro` model.

Changing the model to `text-bison` throws an error:
```
ClientError: [VertexAI.ClientError]: got status: 400 Bad Request

      at throwErrorIfNotOK (node_modules/@google-cloud/vertexai/src/index.ts:518:11)
      at GenerativeModel.generateContentStream (node_modules/@google-cloud/vertexai/src/index.ts:441:5)
```

**Comment by yyyu-google** [comment]
Thank you @aaronzhongg for reaching out. 

At the moment of this comment, this SDK only supports gemini models, text-bison is not supported.

**Comment by cgorrieri** [comment]
This should me mentioned in the README, I wasted so much time.
