### ISSUE TITLE
unhandledRejection: Error [GoogleGenerativeAIError]: [VertexAI.GoogleGenerativeAIError]: exception appending chat history

### ISSUE THREAD

**Issue by AsmaraRP** [googleapis/nodejs-vertexai#139]
I got an error detail like this:

- error unhandledRejection: Error [GoogleGenerativeAIError]: [VertexAI.GoogleGenerativeAIError]: exception appending chat history
    at /Users/{user}/node/{projectfile}/{project-repo}/node_modules/@google-cloud/vertexai/build/src/index.js:219:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
  
 Does anyone have a solution to the problem?

**Comment by marius-ciocoiu** [comment]
Having the same problem. 


```
    const chat = generativeModel.startChat({
        history: [
            {
                role: "user",
                parts: [
                    {
                        text: "How are you doing today?",
                    },
                ],
            },
        ],
    });
```

**Comment by AsmaraRP** [comment]
I've been solved this problem with running this "gcloud auth application-default login", and downgrade from 0.2.1 to 0.1.3

**Comment by marius-ciocoiu** [comment]
Error Response:
```json
{
  "error": {
    "code": 400,
    "message": "Please ensure that multiturn requests alternate between user and model.",
    "status": "INVALID_ARGUMENT"
  }
}

The error response from the initial request to the API indicates an issue with the sequence of messages in the payload. The API expects a strict alternation between 'user' and 'model' roles within the conversation history.

The issue stems from the message history containing back-to-back 'user' role messages, especially when the last message in the history is also attributed to the 'user'. This conflicts with the API's expectations since it anticipates the next turn to be from the 'model'.

To correct this problem, we need to adjust the way we assemble the message history for the request:

1. Confirm the alternation of 'user' and 'model' messages throughout the history.
2. Ensure the last message in the history is from the 'model'.

Proposed improvement:
1. Implement a check to verify proper alternation of message roles before dispatching the request.
2. If the validation detects consecutive 'user' messages or that the last message is from the 'user', it should not make the request and it should return a custom error message that clearly identifies the issue with the message sequence to the user.

**Comment by yyyu-google** [comment]
Hi all,
Thank you for the feedback, while I am prioritizing this issue in planning, a quick way to get diagnosis like https://github.com/googleapis/nodejs-vertexai/issues/139#issuecomment-1923312087 is to use a curl command and see the raw response from endpoint.

**Comment by JCMais** [comment]
thanks @yyyu-google!

**Comment by IchordeDionysos** [comment]
> Hi all, Thank you for the feedback, while I am prioritizing this issue in planning, a quick way to get diagnosis like [#139 (comment)](https://github.com/googleapis/nodejs-vertexai/issues/139#issuecomment-1923312087) is to use a curl command and see the raw response from endpoint.

Well problem is if it's not happening locally but only when deployed ...

**Comment by yyyu-google** [comment]
Hi all,
I have release `0.4.0`. It should bubble up the complete error message now.

**Comment by afzaale01** [comment]
Facing the same error in version 1.1.0 @yyyu-google

**Comment by jjdelorme** [comment]
Same here with version 1.1.0.  The error is very opaque, only "exception posting request to model":
```
GoogleGenerativeAIError: [VertexAI.GoogleGenerativeAIError]: exception posting request to model
    at /my-dir/node_modules/@google-cloud/vertexai/src/functions/generate_content.ts:87:11
```

**Comment by NFNChris** [comment]
I found that the lack of descriptive error for me was due to an older version of Node (v10) running in the deployed environment.  When I updated to Node v20 I was able to debug the error (which happened in my case to be the wrong model name).

**Comment by ulimonte05** [comment]
Hey Chris, have you solved it?
