### ISSUE TITLE
UsageMetadata type definition is actually wrong

### ISSUE THREAD

**Issue by JCMais** [googleapis/nodejs-vertexai#144]
#### Environment details

  - Programming language: TS
  - OS: WSL
  - Language runtime version: 18
  - Package version: 0.2.1

#### Steps to reproduce

  1. make any API request to generate content using gemini-pro
  2. observe the usageMetadata field

The type definitions says that this is the shape it should have:
https://github.com/googleapis/nodejs-vertexai/blob/c90203d153407daa08763c273a827a5e9db54a70/src/types/content.ts#L357C1-L367C2

But this is what I received on that field:
```json
{
  "promptTokenCount": 8434,
  "candidatesTokenCount": 9,
  "totalTokenCount": 8443
}
```

**Comment by yyyu-google** [comment]
Hi @JCMais 
version `0.5.0` should fix this problem.
