### ISSUE TITLE
Question: best practices for handling chat sessions

### ISSUE THREAD

**Issue by ipeychev** [googleapis/nodejs-vertexai#191]
Hello!

I see that `GenerativeModel` class has `startChat` method, but there is no, e.g., `endChat`. 

Here are my questions:
1. Does that mean the developer is not required to care about terminating the chat session somehow?
2. How many chat sessions can be open simultaneously?

Best regards,

**Comment by happy-qiao** [comment]
> Does that mean the developer is not required to care about terminating the chat session somehow?

Yes

> How many chat sessions can be open simultaneously?

No limit on chat sessions numbers in the SDK side. Actually the ChatSession class stores the history and you can create as many instances as you want.

**Comment by ipeychev** [comment]
Awesome!
