### ISSUE TITLE
Support for custom headers & base url

### ISSUE THREAD

**Issue by colegottdank** [googleapis/nodejs-vertexai#258]
**Problem**
Integrating with any LLM monitoring and observability platform with a proxy implementation is extremely difficult with the current version of vertexai's SDK. These proxies provide great features for developers and businesses using LLMs, so adding support for them would be great.

**Solutions**
- Adding the ability to add custom headers to the RequestOptions object
- Adding the ability to override the baseUri. Not the path, just the baseUri.

Both of the above are supported in OpenAI's SDK.

**Alternatives**
The alternatives involve monkey patching generateContent and every method it uses. Or overriding the global fetch, appending headers and changing baseUri.

**Additional context**
Here is an example of how OpenAI supports the custom headers and baseUri: https://docs.helicone.ai/getting-started/integration-method/openai-proxy

Click on the node implementation:

```typescript
const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
    basePath: "https://oai.hconeai.com/v1",
    baseOptions: {
      headers: {
          "Helicone-Auth": `Bearer ${process.env.HELICONE_API_KEY}`,
      },
    },
});
```

**Comment by colegottdank** [comment]
Hi! @yyyu-google, any update on the status of this?

**Comment by yyyu-google** [comment]
base url is supported in [apiEndpoint](https://github.com/googleapis/nodejs-vertexai/blob/ca43e2f0b4ebef60d3739b10a3707cdfe2e2a4ec/src/types/content.ts#L34) field. You can use it when instantiating VertexAI class

```
const vertexAI = new VertexAI({
   // your other parameters
  // your base url
  apiEndpoint: "your base url"
});
```

for custom headers, if your intent is to include authentication options, you can pass your authentication via [googleAuthOptions](https://github.com/googleapis/nodejs-vertexai/blob/ca43e2f0b4ebef60d3739b10a3707cdfe2e2a4ec/src/types/content.ts#L41). A full list of GoogleAuth Options is [here](https://github.com/googleapis/google-auth-library-nodejs/blob/main/src/auth/googleauth.ts). Usage is 

```
const vertexAI = new VertexAI({
   // your other parameters
  // your authentication options
  googleAuthOptions: <Your authentication options>
});
```

**Comment by colegottdank** [comment]
Hi,

The apiEndpoint looks like it will work, thanks! 

For the custom headers, the intent is to include the bearer token of the LLM monitoring application. It gets passed in like this:

`Helicone-Auth`: `Bearer {HELICONE_API_KEY}`

However, the LLM monitoring applications still require the `Authorization` header to be set to the provider's auth, in this case, Gemini's token. 

So, will just need to ability to pass in the other header. Is there a way to do that?

**Comment by yyyu-google** [comment]
I see, we will have the support of custom header soon. I will update here once the work is release.

**Comment by colegottdank** [comment]
Hi @yyyu-google, I created a pull request to hopefully speed this along :) Thank you!

https://github.com/googleapis/nodejs-vertexai/pull/297

**Comment by yyyu-google** [comment]
Hi @colegottdank 
This commit https://github.com/googleapis/nodejs-vertexai/commit/b47d733680837233b4323f4113737421099df02b enables custom headers

Example

```typescript
import {VertexAI, RequestOptions} from '@google-cloud/vertexai'

const vertexAI = new VertexAI({
  // parameters here. see docs https://cloud.google.com/nodejs/docs/reference/vertexai/latest/vertexai/vertexai
});

const customerHeaders = new Headers({
  // your header config
});

const requestOptions = {
  customerHeaders: customerHeaders
} as RequestOptions;

const model = vertexAI.getGenerativeModel(
  {model: 'gemini-1.0-pro'}, // or other models you'd like to try out
  requestOptions
);
```

I will release the commit https://github.com/googleapis/nodejs-vertexai/commit/b47d733680837233b4323f4113737421099df02b in several days.

**Comment by colegottdank** [comment]
Yayayay! Thank you @yyyu-google!!!
