### ISSUE TITLE
add response_mime_type to GenerationConfig

### ISSUE THREAD

**Issue by 0xDing** [googleapis/nodejs-vertexai#306]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**

The `GenerationConfig` as described in the [API reference](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference) includes new features such as response_mime_type and seed. However, these features are currently not available in the SDK. Could these be implemented or updated in the SDK to match the documentation?

**Describe alternatives you've considered**

Fork it

**Additional context**

**Comment by Markus-ipse** [comment]
We're currently battling with inconsistent JSON output, as the model has a tendency to either wrap the response in backticks or adding comments about the JSON response outside of the actual JSON blob.

I am really hoping being able to specify response_mime_type will solve these issues

**Comment by Giasinit** [comment]
I keep getting this response:
` GoogleGenerativeAIError: [VertexAI.GoogleGenerativeAIError]: got status: 500 Internal Server Error. {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}`

**Comment by deathemperor** [comment]
Just checked and the 500 issue has been resolved

**Comment by Giasinit** [comment]
@deathemperor i see.. thanks

**Comment by Giasinit** [comment]
@3lue9 we solved the problem finally LOL.
I will explain later, in the meantime read the discussion to understand what I am referring to.

**Comment by tamerxkilinc** [comment]
@Giasinit Could you share your solution with me? Having the same problem currently.

**Comment by Giasinit** [comment]
> @Giasinit Could you share your solution with me? Facing the same problem.

@tamerxkilinc, if you want, you can share you code, to figure out what language you are using, and what configuration!

**Comment by tamerxkilinc** [comment]
For us the solution mentioned above is working. Just adding response_mime_type to generationConfig and declaring it as any works and gives us no errors.

**Comment by Firdaus-prog** [comment]
Today, Its not working for us anymore ☹:

ERROR	Invoke Error 	
{
    "errorType": "GoogleGenerativeAIError",
    "errorMessage": "[VertexAI.GoogleGenerativeAIError]: got status: 500 Internal Server Error. {\"error\":{\"code\":500,\"message\":\"Internal error encountered.\",\"status\":\"INTERNAL\"}}",
    "name": "GoogleGenerativeAIError",
    "stack": [
        "GoogleGenerativeAIError: [VertexAI.GoogleGenerativeAIError]: got status: 500 Internal Server Error. {\"error\":{\"code\":500,\"message\":\"Internal error encountered.\",\"status\":\"INTERNAL\"}}",
        "    at throwErrorIfNotOK (file:///var/task/src/functions/vertexai-generate-insights.mjs:57113:15)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async generateContent (file:///var/task/src/functions/vertexai-generate-insights.mjs:57573:7)",
        "    at async generateCallInsights (file:///var/task/src/functions/vertexai-generate-insights.mjs:71188:21)",
        "    at async lambdaHandler (file:///var/task/src/functions/vertexai-generate-insights.mjs:71472:22)",
        "    at async runRequest (file:///var/task/src/functions/vertexai-generate-insights.mjs:71396:27)"
    ]
}

**Comment by Giasinit** [comment]
@Firdaus-prog may you share with us your code?

**Comment by Firdaus-prog** [comment]
Sorry everyone @Giasinit  , the issue turned out to be something related to the files we were referencing and we incorrectly assumed it was related to the addition of `responseMimeType` in the request.

**Comment by tamerxkilinc** [comment]
For me it looks like adding this parameter should never cause an error, because the underlying post request just stringifies the request-options including the generationConfig. 

https://github.com/googleapis/nodejs-vertexai/blob/6b3e68e3b869659d17ef584995de7d7bfc1b1f3b/src/functions/post_request.ts#L35-L82

https://github.com/googleapis/nodejs-vertexai/blob/6b3e68e3b869659d17ef584995de7d7bfc1b1f3b/src/functions/generate_content.ts#L50-L94

**Comment by snehathakur07** [comment]
I am facing the same issue, getting 500. It was working fine a few days back until I tested it today. It's not working anymore. When i remove the response mime type, theres no 500 error. Could anybody suggest somethin

import { GoogleGenerativeAI } from "@google/generative-ai";
import { FunctionDeclarationSchemaType} from '@google/generative-ai' ;

import dotenv from "dotenv"
dotenv.config();

const apiKey=process.env.API_KEY
const genAI = new GoogleGenerativeAI(apiKey);

//for summary
let model = genAI.getGenerativeModel({
  model: "gemini-1.5-pro",
  generationConfig: {
    responseMimeType: "application/json",
    responseSchema: {
      type: FunctionDeclarationSchemaType.ARRAY,
      items: {
        type: FunctionDeclarationSchemaType.OBJECT,
        properties: {
          title: {
            type: FunctionDeclarationSchemaType.STRING,
          },
          summary:{
            type: FunctionDeclarationSchemaType.STRING,
          },
        },
      },
    },
  }
});


async function runSummary(prompt){
  const result = await model.generateContent(prompt)
  const response=result.response;
  return response.text(); 
}
export default runSummary;

**Comment by happy-qiao** [comment]
responseMimeType is added at https://github.com/googleapis/nodejs-vertexai/releases/tag/v1.4.0

**Comment by DSep** [comment]
Re:

> The GenerationConfig as described in the [API reference](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference) includes new features such as response_mime_type and seed. However, these features are currently not available in the SDK. Could these be implemented or updated in the SDK to match the documentation?

@happy-qiao Is the seed parameter shelved?
