### ISSUE TITLE
VertexAI ReferenceError : headers is not defined [ Solution !]

### ISSUE THREAD

**Issue by ToonKru3** [googleapis/nodejs-vertexai#332]
for who have error like this => ReferecneError : Headers is not defined , you have to check node.js version : v16.13.1 and it's error like this  after i change version to latest version is gone , so please enjoy
![Node-version](https://github.com/googleapis/nodejs-vertexai/assets/56877894/d95cb209-a16b-403c-82c6-75e661277cda)

**Comment by yyyu-google** [comment]
Hi @ToonKru3 
Thank you the report. I have included the node.js version requirement in the README file in https://github.com/googleapis/nodejs-vertexai/pull/337 . I hope other fellows won't need to struggle on the same issue.

**Comment by yyyu-google** [comment]
Hi @ToonKru3 
It has been more than a month since I updated the README. I will mark this as closed. Thank you again for bringing this up.

**Comment by edgarsbarajas** [comment]
Thank you! I was banging my head against the wall trying to figure this error out. Turns out I just needed to move from Node 14 to Node 20.
