### ISSUE TITLE
Still not able to pass a string as systemInstruction

### ISSUE THREAD

**Issue by sebiweise** [googleapis/nodejs-vertexai#350]
#### Environment details

  - Programming language: NextJs/Node
  - OS: Windows and Ubuntu
  - Language runtime version: v20.11.1
  - Package version: "^1.2.0"

#### Steps to reproduce
```typescript
    const generativeModel = vertexai.getGenerativeModel({
        model: modelName,
        generationConfig,
        // TODO: Add systemInstruction
        // systemInstruction: {
        //     role: "system",
        //     parts: [{ text: systemPrompt }],
        // },
        systemInstruction: systemPrompt,
        safetySettings: [
            {
                category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE
            },
            {
                category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE
            },
            {
                category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
                threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE
            },
            {
                category: HarmCategory.HARM_CATEGORY_HARASSMENT,
                threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE
            }
        ],
    });
```
![image](https://github.com/googleapis/nodejs-vertexai/assets/22999200/1923f2a6-6f0a-4875-99f9-c35687b6d045)

However when I try to send a content object instead of the string, I´m getting a Bad Request:
`ClientError: [VertexAI.ClientError]: got status: 400 Bad Request. {"error":{"code":400,"message":"The input system_instruction is not supported.","status":"INVALID_ARGUMENT"}}`

Models:
- gemini-1.0-pro
- gemini-1.0-pro-vision

**Comment by guchenhe** [comment]
https://github.com/googleapis/nodejs-vertexai/issues/350

**Comment by happy-qiao** [comment]
@sebiweise I tested systemInstruction, it works. Please update your nodejs-vertexai package version and try again

![image](https://github.com/user-attachments/assets/2b1a4e0c-c45c-445f-96e7-6f9c2acc55d4)

Thanks

**Comment by sebiweise** [comment]
Yes the 1.5.0 release fixed the issue. Thanks for the response.
