### ISSUE TITLE
Context Caching

### ISSUE THREAD

**Issue by cabljac** [googleapis/nodejs-vertexai#468]
I'm trying to use the Context Caching feature of the API through this SDK. Is this supported, and if so are there docs on this?

**Comment by timconnorz** [comment]
@cabljac  Check this comment out:

https://github.com/googleapis/nodejs-vertexai/issues/395#issuecomment-2383393813

**Comment by cabljac** [comment]
@timconnorz thanks! There seemed to be a small bug in the SDK which I fixed here https://github.com/googleapis/nodejs-vertexai/pull/469
