### ISSUE TITLE
Add support for customising authentication options

### ISSUE THREAD

**Issue by markacola** [googleapis/nodejs-vertexai#75]
Is it possible to expose additional options via the `VertexAI` constructor? Like `keyFilename` to pass through to the constructed `GoogleAuth` instance.

E.g. I am unable to authenticate with a key file like I do with the [EndpointServiceClient](https://github.com/googleapis/google-cloud-node/blob/6db06cbbcac4bffd9dd8947356623e4d95e6ed46/packages/google-cloud-aiplatform/src/v1/endpoint_service_client.ts#L86C56-L86C58) from `@google-cloud/aiplatform`.

This would make the library a much easier drop-in replacement/addition to the `@google-cloud/aiplatform` package.

**Comment by sararob** [comment]
Thanks for raising this, we'll work on adding support for more auth options.

**Comment by sararob** [comment]
Expanded auth support is now available in the latest `0.2.0` release. Closing this issue, thanks for the feedback!
