### ISSUE TITLE
When using Japanese with vertex_ai.preview.getGenerativeModel, REPLACEMENT CHARACTERS are displayed.

### ISSUE THREAD

**Issue by Arahabica** [googleapis/nodejs-vertexai#78]
When using Japanese with vertex_ai.preview.getGenerativeModel, REPLACEMENT CHARACTERS are displayed.

#### Environment details

  - Programming language: JavaScript (Node.js)
  - OS: macOS Ventura 13.6.1 (Apple M1)
  - Language runtime version: Node.js v18.19.0
  - Package version: `@google-cloud/vertexai` version 0.1.3

#### Steps to reproduce

1. Use Japanese with vertex_ai.preview.getGenerativeModel.
2. Observe that the response displays REPLACEMENT CHARACTERS as shown below:

```
豊臣秀吉（1537年-1598年���は、日本の戦国時代から安土桃山時代にかけて活躍した������・大名・政治家です。
```

**Comment by Arahabica** [comment]
I use `gemini-pro-vision` model.

**Comment by Arahabica** [comment]
It seems like the issue might be due to simple string concatenation here.
https://github.com/googleapis/nodejs-vertexai/blob/9546fe6aed5f647495cc8f511dd78f56f6755a35/src/process_stream.ts#L45

**Comment by sararob** [comment]
This should have been fixed by https://github.com/googleapis/nodejs-vertexai/pull/86. Could you confirm by installing from main via `npm install "https://github.com/googleapis/nodejs-vertexai"` and sending the same request you tried before?

**Comment by Arahabica** [comment]
@sararob 
I have confirmed that the problem is fixed.
Thank you!

**Comment by sararob** [comment]
Thanks for confirming! I'll close this issue.
