### ISSUE TITLE
How can I use Semantic Retriever and Function calling from nodejs-vertexai?

### ISSUE THREAD

**Issue by ipeychev** [googleapis/nodejs-vertexai#81]
Hello,

How can I use the [Function calling](https://ai.google.dev/docs/function_calling) and [Semantic Retriever](https://ai.google.dev/docs/semantic_retriever) with Gemini and using `nodejs-vertexai` API? I didn't see any examples or exported functions/classes. There is only Python or raw [CURL samples](https://ai.google.dev/docs/function_calling#function-calling-curl-samples) for Function calling.

Thanks,
Iliyan

**Comment by ipeychev** [comment]
Thank you, Sara. And, about the Semantic Retriever? Are there plans to be added here too?

**Comment by yyyu-google** [comment]
Hi @ipeychev 
Thank you for your interest in trying out!
Function calling is enabled in this SDK now. Please see README section [here](https://github.com/googleapis/nodejs-vertexai?tab=readme-ov-file#function-calling). 

As for Semantic Retriever, we will update to our release note and README file when it is ready. Stay tuned :)

I am closing this comment now.
